[package]
name = "mogging"
version = "0.1.0"
edition = "2021"

[lib]
name = "mogging"
path = "src/lib.rs"

[dependencies]
assert_cmd = "2.0.16"
chrono = "0.4.40"
crossterm = "0.28.1"
instant = "0.1.13"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
